### PR TITLE
Issue-16-Configurable-TOF-Polling-Rate

### LINKED ISSUE #16: Add Particle Function to Lower TOF Polling Rate

### PR DESCRIPTION
**Pull request by orbitllc**
v12 - Breaking change - requires Gateway v21.5 or later - gateway can now configure TOF polling rate through particle command (see README of gateway)

EDIT: NOT a breaking change. It just makes the particle command options out of sync with gateway options

### CODE REVIEW

**Comment by chipmc** [comment]
@orbitllc , I see what you are working to do here and I think this is on the right track.  But, I have some questions that we may want to address in the comments for clarity:
- It is called polling rate but the units are mSec not pulses / second.  
- There is a minimum for each range regime (short, med, long) - why would this be the case for a polling rate

What it feels like is we are setting a time of flight value with shorter range needing less time and longer ranges needing more time.  The rate would be impacted by this value but it is not clear why medium and long range do not have different minimums.  

Perhaps there could be a link to the documentation on this feature.

**Comment by orbitllc** [comment]
Hey Chip,

The minimums were taken straight from the data sheet for the TOF sensor when I wrote this initially.

I will definitely add a link to that documentation in the comments!

The ‘polling rate’ is actually the ‘timing budget’ set through the library in microseconds. Timing budget meaning, the amount of time allotted to each ranging operation. It is unclear why, but medium and long have the same minimum timing budget.

I could change this variable to pulses/second and do the math from there if you would like it in those units!

Thanks for the review

**Comment by orbitllc** [comment]
Correction:

NOT a breaking change. It just makes the particle command options out of sync with gateway options

**Comment by orbitllc** [comment]
Going to merge this to master - if detection zone is too slow for proper counting, raise the TOF_DEFAULT_DETECTIONS_PER_SECOND variable in Config.h and reflash


I have made this as quick as possible, as in:

- If the detectionZone detects someone, it IMMEDIATELY takes an occupancy measurement (zone 0-1-3-2-0 thing) within the same TofSensor::loop() 

- if occupancyState is 0 at the beginning of the TofSensor::loop(), it will detect instead of measure. Effectively, the maximum polling rate will never measure more than 1 'occupancyState  0', and further 0s are 'detections', which are pulse limited

**Comment by orbitllc** [comment]
**This is actually NOT a breaking change. It just makes the particle command options out of sync with gateway options**

Merged this to master - if detection zone is too slow for proper counting, raise the TOF_DEFAULT_DETECTIONS_PER_SECOND variable in Config.h and reflash

I have made this as quick as possible, as in:

If the detectionZone detects someone, it IMMEDIATELY takes an occupancy measurement (zone 0-1-3-2-0 thing) within the same TofSensor::loop()

if occupancyState is 0 at the beginning of the TofSensor::loop(), it will detect instead of measure. Effectively, the maximum polling rate will never measure more than 1 'occupancyState 0', and further 0s are 'detections', which are pulse limited

**Pull request merged**
